### ISSUE TITLE
Fix microapps direct url link redirect

### ISSUE THREAD

**Issue by devYaoYH** [googleinterns/scan-and-go#11]
Works: https://microapps.google.com/1971992074819089602
Doesn't: https://microapps.google.com/1971992074819089602?link=store%3Fid%3DWPANCUD-1
expected to redirect to: https://scan-and-go-for-gpay.an.r.appspot.com/store?id=WPANCUD-1
*note url encoding for '?' and '='

**Comment by redhoteggplant** [comment]
both links redirect to https://pay.google.com/intl/en_in/about/ for me, is that supposed to happen?

**Comment by BhavyaLight** [comment]
https://pay.google.com/intl/en_in/about/  is the fallback link that opens when the app is not installed in the device

**Comment by BhavyaLight** [comment]
@devYaoYH yes this link wont work as it is:  https://microapps.google.com/1971992074819089602?link=store%3Fid%3DWPANCUD-1

to go into the microapp.

You need to wrap this link around a FDL (firbasedynamiclink) and only that can allow it to go into the app.

**Comment by BhavyaLight** [comment]
Can you try these and lmk if any work: https://gpay.app.goo.gl/hf2Sf4
https://gpay.app.goo.gl/1yxMVJ

**Comment by devYaoYH** [comment]
Configuration change was necessary to whitelist deeplinks. Now, https://microapps.google.com/1971992074819089602?link=store%3Fid%3DWPANCUD-1%26mid%3DWPANCUD will directly link into a store page to scan products. Which we can encode into QR for display (e.g.):
![TestStore_DirectQR](https://user-images.githubusercontent.com/5269791/84375981-eafc1800-ac12-11ea-9b66-868b418f0acb.png)
