### ISSUE TITLE
Maps API key leaked

### ISSUE THREAD

**Issue by RiRa12621** [googleinterns/scan-and-go#110]
https://github.com/googleinterns/scan-and-go/blob/3f3e146297ac9440ad76e211b5c0ecbb9a9fde4b/client/public/index.html#L28

You have hardcoded an commited your maps API key which is bad practice.

Here's some more context around it https://medium.com/bugbountywriteup/unauthorized-google-maps-api-key-usage-cases-and-why-you-need-to-care-1ccb28bf21e

**Comment by devYaoYH** [comment]
To clarify, so far the HTTP Referrers setting is enabled and has been restricted to our AppEngine domain

**Comment by RiRa12621** [comment]
Nice, that's not obvious at first glance from an external perspective and I thought I'd rather flag it.

**Comment by devYaoYH** [comment]
No worries, thanks for raising the issue :) We are moving to more securely authenticated API calls as the project develops.
