### ISSUE TITLE
[ScanStore] Uncaught error when adding a nonexisting item 

### ISSUE THREAD

**Issue by redhoteggplant** [googleinterns/scan-and-go#186]
Adding an item that does not exist in the database results in `TypeError: Cannot read property 'toFixed' of undefined`.

Replace 
`    if (item) {`
with
`    if (item && Object.keys(item).length > 0) {`
in [ScanStore.tsx](https://github.com/googleinterns/scan-and-go/blob/c83d2443d5fa5484fa7f0bd18020db9e081b6ec3/client/src/pages/ScanStore/ScanStore.tsx#L94)

and add a test for this!

Reference: [testing for empty object in JS](https://stackoverflow.com/questions/679915/how-do-i-test-for-an-empty-javascript-object)

**Comment by devYaoYH** [comment]
Thanks for noticing this! Fix merged :)
testing returned item validity with presence of `barcode` field: `if (item.barcode)`
