### ISSUE TITLE
[Typography - Font Family] Change to Google Sans Display

### ISSUE THREAD

**Issue by redhoteggplant** [googleinterns/scan-and-go#210]

**Comment by devYaoYH** [comment]
closest I'm finding is a font called: Product Sans
A .ttf file can be found in a [github repo](https://github.com/google/iosched-ios/blob/master/Source/IOsched/ProductSans-Regular.ttf)
*note: apparently not released as open-source font? [source](https://en.wikipedia.org/wiki/Product_Sans#License)
**If we do need to use this extensively, we should check with internal to see how we can serve this font**

**Comment by devYaoYH** [comment]
resolved, font is served from fonts.googleapis CDN but not publicly listed on fonts.google.com
