### ISSUE TITLE
Configure deployment of app from github

### ISSUE THREAD

**Issue by BhavyaLight** [googleinterns/scan-and-go#33]
- Allow only approved code in production

**Comment by devYaoYH** [comment]
https://github.com/GoogleCloudPlatform/github-actions/blob/master/setup-gcloud/README.md
Might need to resolve:

> Create failed. Error 400: Key creation is not allowed on this service account.

Before we can deploy using github actions

**Comment by devYaoYH** [comment]
Proposed Workaround:
- Spin up a compute engine (this will have default credentials loaded if I'm not wrong)
- Github action to push to locally hosted .git repo on said compute engine
- build and gcloud app deploy with custom git hook written for that repo

**Comment by devYaoYH** [comment]
Currently configuring via Google Cloud Build and cloudbuild.yaml
