### ISSUE TITLE
Pull static assets like css, images, svgs into a separate folder

### ISSUE THREAD

**Issue by BhavyaLight** [googleinterns/scan-and-go#7]

**Comment by devYaoYH** [comment]
Does this reference our development environment or built environment? `yarn build` automatically collates and places static assets into respective separate folders under `build/static`. This build folder is in our `.gitignore` hence not visible in repo.

**Comment by BhavyaLight** [comment]
just the dev environment as well, would be good to start giving it some structure!

**Comment by devYaoYH** [comment]
#9 Moved css and img assets into respective folders in /client/src
