### ISSUE TITLE
[API AUTH] [Design doc] How to pass user information in authentication headers

### ISSUE THREAD

**Issue by BhavyaLight** [googleinterns/scan-and-go#91]
User identifying information such as userId or any authentication token should not be passed directly in GET or POST parameters as anyone can see what is going throgh. 

It would be good to support the proper authentication using GCP for users. Let's start with a design doc and implement that for our API's!
Basic explanation with some history:  https://blog.restcase.com/restful-api-authentication-basics/
JWTS: https://jwt.io/introduction/ , https://blog.logrocket.com/jwt-authentication-best-practices/
GCP & JWTS: https://cloud.google.com/endpoints/docs/openapi/service-account-authentication

**Comment by devYaoYH** [comment]
Authentication Design Doc initialized: go/gpay3-scanandgo-server-auth
